# -*- coding: utf-8 -*-
"""LidarTrainLibrary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6OH_YHPxmYyFCbljUpHiVfp4ylLhmIW
"""

import os
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F

from scipy.ndimage import maximum_filter

from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/MyDrive/LIDAR_Fusion/lidarenv/lib/python3.12/site-packages')

from nuscenes.nuscenes import NuScenes
from nuscenes.utils.data_classes import LidarPointCloud, Box
from nuscenes.eval.detection.utils import category_to_detection_name
from nuscenes.utils.geometry_utils import points_in_box

from pyquaternion import Quaternion
from objectron.dataset.iou import IoU as IoU3d
from objectron.dataset.box import Box as BoxIoU

from lidar_baseline import get_ij, get_point_pillar


def load_sweeps(nusc, sample, N=10, min_distance = 1.0):

  pc, times = LidarPointCloud.from_file_multisweep(nusc=nusc, sample_rec = sample, chan = "LIDAR_TOP", ref_chan = "LIDAR_TOP", nsweeps = N, min_distance = min_distance)

  out = np.concatenate([pc.points, times], axis =0).T

  return out

def get_grid_attr(cloud, voxel_size = 1):

  min_x = np.min(cloud[:, 0:1])
  min_y = np.min(cloud[:, 1:2])
  min_z = np.min(cloud[:, 2:3])

  min_bound = np.array([min_x,min_y,min_z])

  max_x = np.max(cloud[:, 0:1])
  max_y = np.max(cloud[:, 1:2])
  max_z = np.max(cloud[:, 2:3])

  max_bound = np.array([max_x, max_y, max_z])

  pc_range = max_bound - min_bound

  grid_shape = np.ceil((max_bound - min_bound) / voxel_size).astype(int)

  return min_bound, max_bound, grid_shape, pc_range

def transform_cloud(cloud, pc_range =[-51.2,-51.2,51.2,51.2]):
  min_bound, max_bound, _, _= get_grid_attr(cloud)

  min_x, min_y = min_bound[0], min_bound[1]
  max_x, max_y = max_bound[0], max_bound[1]

  min = np.array([min_x, min_y])
  max = np.array([max_x, max_y])

  out = cloud.copy()
  out[:,:2] = out[:, :2] - min[None,:]

  out[:,:2] = out[:, :2] / (max - min)[None,:]
  out[:,:2] = out[:,:2] - 0.5

  out[:,:2] = out[:,:2]*2 * pc_range[2]

  return out

def get_pillars(cloud, voxel_size = 1, pillar_max = 100): #voxel_size is length of one side of voxel

  min_bound, max_bound, grid_shape, _ = get_grid_attr(cloud, voxel_size=voxel_size)

  T = grid_shape[0]*grid_shape[1]

  N_counter = np.zeros(T)

  for k in range(cloud.shape[0]):
    point = cloud[k]

    p_index = get_point_pillar(point, min_bound, voxel_size, grid_shape[0])

    N_counter[p_index] += 1

  N = (np.max(N_counter)).astype(int)

  if pillar_max < N or pillar_max == None:
    N = pillar_max

  out = np.zeros((T, N, 5))

  mask = np.zeros((T), dtype = int)

  for m in range(cloud.shape[0]):
    point = cloud[m]

    p_index = get_point_pillar(point, min_bound, voxel_size, grid_shape[0])

    k = mask[p_index]

    if k < N:
      out[p_index][k] = point

      mask[p_index] += 1

  out_zeros = ~np.all(out == 0, axis=(1, 2))

  out = out[out_zeros,:,:]

  mask = mask[mask != 0] #mask returns how many non-padded points are in each pillar. Zero points in a pillar are assumed to be padded unless the mask indicates otherwise

  out = torch.from_numpy(out).float()
  mask = torch.from_numpy(mask).float()

  coords = torch.zeros(out.shape[0], 3)
  
  for i in range(out.shape[0]):
    coords[i] = torch.sum(out[i][:,0:3], dim = 0)/mask[i]

  return out, coords, mask

def get_yaw(q):
  v = q.rotate(np.array([1,0,0]))
  return np.arctan2(v[1],v[0])

def get_boxes_max_min(boxes):

  x_min = boxes[0].center[0]
  y_min = boxes[0].center[1]
  x_max = boxes[0].center[0]
  y_max = boxes[0].center[1]
  z_min = boxes[0].center[2]
  z_max = boxes[0].center[2]

  for box in boxes:

    if box.center[0] < x_min:
      x_min = box.center[0]

    if box.center[1] < y_min:
      y_min = box.center[1]

    if box.center[2] < z_min:
      z_min = box.center[2]

    if box.center[0] > x_max:
      x_max = box.center[0]

    if box.center[1] > y_max:
      y_max = box.center[1]

    if box.center[2] > z_max:
      z_max = box.center[2]

  return x_min, y_min, x_max, y_max, z_min, z_max

def category_to_label(category):
  categories = ["barrier", "bicycle", "bus", "car", "construction_vehicle", "motorcycle", "pedestrian", "traffic_cone", "trailer", "truck"]

  try:
    label = categories.index(category)
  except ValueError:
    label = 0

  return label

def process_boxes(nusc, sample, boxes, cloud, threshold = 1):

  ego_pose = nusc.get("ego_pose", sample["data"]["LIDAR_TOP"])

  sd_rec = nusc.get('sample_data', sample['data']['LIDAR_TOP'])
  cal_sensor = nusc.get('calibrated_sensor', sd_rec['calibrated_sensor_token'])

  out_boxes = []

  valid_boxes = []

  cloud_xyz = cloud[:,:3].T

  for box in boxes:
    category_name = box.name

    detection_name = category_to_detection_name(category_name)

    box.translate(-np.array(ego_pose['translation']))
    box.rotate(Quaternion(ego_pose['rotation']).inverse)

    box.translate(-np.array(cal_sensor['translation']))
    box.rotate(Quaternion(cal_sensor['rotation']).inverse)

    box.name = detection_name

    out_boxes.append(box)

  for box in out_boxes:
      indices = points_in_box(box, cloud_xyz)
      num_pts = np.sum(indices)

      if num_pts >= threshold and box.name != None:

        label = category_to_label(box.name)
        box.label = label

        valid_boxes.append(box)

  return valid_boxes

def splat_gaussian(heatmap, center, sigma):

  r = heatmap.shape[0]

  x_axis = torch.arange(0, r, device=heatmap.device, dtype=torch.float32)
  y_axis = torch.arange(0, r, device=heatmap.device, dtype=torch.float32)
  y_grid, x_grid = torch.meshgrid(y_axis, x_axis, indexing='ij')

  distances_squared = torch.zeros((r,r), device=heatmap.device)

  distances_squared += (x_grid-center[0])**2 +(y_grid-center[1])**2

  gaussian = torch.exp((-1*distances_squared)/(2*sigma**2))

  outmap = np.maximum(heatmap, gaussian)

  return outmap

def gaussian_radius(w, l, threshold = 0.1):

    a1, b1, c1 = 4, -2*(w+l), (1-threshold)*w*l
    r1 = (b1 - np.sqrt(b1**2 - 4*a1*c1)) / (2*a1)

    a2, b2, c2 = 4*threshold, 2*threshold*(w+l), -(1-threshold)*w*l
    r2 = (-b2 + np.sqrt(b2**2 - 4*a2*c2)) / (2*a2)

    a3, b3, c3 = 1, -(w+l), (1-1/threshold)*w*l
    r3 = (b3 + np.sqrt(b3**2 - 4*a3*c3)) / (2*a3)

    return max(min(r1, r2, r3),2)


def target_generation(gt_boxes, heatmap_resolution = 256, threshold = 0.1, k =10, stride = 2, pc_range = [-51.2, -51.2, 51.2, 51.2], max_objects = 500): 

  box_ij = []
  box_wl = []

  #x_min, y_min, x_max, y_max = pc_range
  x_min, y_min, x_max, y_max, _, _ = get_boxes_max_min(gt_boxes)

  for box in gt_boxes:

    box_x = box.center[0]
    box_y = box.center[1]

    i = np.floor((box_x - x_min)/(x_max - x_min) * (heatmap_resolution - 1))
    j = np.floor((box_y - y_min)/(y_max - y_min) * (heatmap_resolution - 1))

    i = int(i)
    j = int(j)

    box_ij.append([i,j])
    box_wl.append([box.wlh[0], box.wlh[1]])

  sigmas = []

  for i in range(len(box_wl)):
    w = box_wl[i][0]
    l = box_wl[i][1]

    sigma = gaussian_radius(w, l, threshold = threshold)

    sigmas.append(sigma)

  out_heatmaps = torch.zeros((heatmap_resolution, heatmap_resolution, k))

  target_resolution = heatmap_resolution * stride

  offset_target = torch.zeros((target_resolution, target_resolution, 2))
  size_target = torch.zeros((target_resolution, target_resolution, 3))
  z_target = torch.zeros((target_resolution, target_resolution))
  rotation_target = torch.zeros((target_resolution, target_resolution, 2))

  ind = torch.zeros((max_objects))
  mask = torch.zeros((max_objects))
  cat = torch.zeros((max_objects))

  for m in range(len(box_ij)):
    i, j = box_ij[m]

    i, j = i*stride, j*stride
    box = gt_boxes[m]

    if not (0 <= i < target_resolution and 0 <= j < target_resolution):
      continue

    label = box.label

    label_map = out_heatmaps[:,:,label]

    out_heatmaps[:,:,label] = splat_gaussian(label_map, box_ij[m], sigmas[m])

    box_i = (i / (target_resolution - 1) * (x_max - x_min)) + x_min
    box_j = (j / (target_resolution - 1) * (y_max - y_min)) + y_min

    offset_x = box.center[0] - box_i
    offset_y = box.center[1] - box_j
    offset_m = torch.tensor([offset_x, offset_y])

    size_m = torch.log(torch.tensor(box.wlh))

    z_m = box.center[2]

    alpha = box.orientation.radians

    rotation_m = torch.tensor([np.sin(alpha), np.cos(alpha)])

    offset_target[i][j] = offset_m
    size_target[i][j] = size_m
    z_target[i][j] = z_m
    rotation_target[i][j] = rotation_m

    if m < max_objects:
    
      ind[m] = j * target_resolution + i
      mask[m] = 1
      mask[m-1] = 0
      cat[m] = label

  return out_heatmaps, offset_target, size_target, z_target, rotation_target, ind, mask, cat

def loss_hm(heatmap, targetmap, alpha = 2, beta = 4):
  loss_hm = 0

  N = heatmap[heatmap == 1].shape[0]

  for i in range(heatmap.shape[0]):
    for j in range(heatmap.shape[1]):

      if targetmap[i][j] == 1:
        loss_ij = ((1-heatmap[i][j])**alpha)*torch.log(heatmap[i][j])

      else:
        loss_ij = ((1-targetmap[i][j])**beta) * (heatmap[i][j]**alpha) * torch.log(1-heatmap[i][j])

      loss_hm += loss_ij

  return loss_hm * -1 /N

class StageOneLoss(nn.Module):

  def __init__(self, alpha = 2, beta = 4, lambda_reg = 0.25):
    super(StageOneLoss, self).__init__()
    self.alpha = alpha
    self.beta = beta
    self.lambda_reg = lambda_reg
    self.l1loss = nn.L1Loss()

  def forward(self, heatmap_input, reg_input, target_map, target_reg): #batched inputs for all

    total_loss = 0

    for j in range(heatmap_input.shape[0]):

      heatmap_loss = loss_hm(heatmap_input[j], target_map[j], alpha = self.alpha, beta = self.beta)

      reg_loss = self.l1loss(reg_input[j], target_reg[j])

      reg_loss = reg_loss * self.lambda_reg

      total_loss += heatmap_loss + reg_loss

    total_loss = total_loss / input.shape[0]

    return total_loss

class StageTwoLoss(nn.Module):

  def __init__(self):
    super(StageTwoLoss, self).__init__()
    self.l1_loss = nn.L1Loss()
    self.smoothl1 = nn.SmoothL1Loss()

  def forward(self, refine_input, I_input, refine_target, Iou_target):

    total_loss = 0

    for j in range(input.shape[0]):

      offset_loss = self.l1loss(refine_input, refine_target)

      confidence_loss = self.smoothl1(I_input, Iou_target)

      total_loss += offset_loss + confidence_loss

    return total_loss / input.shape[0]

def get_samples(start, stop, nusc, dataroot):
  samples = []

  for i in range(start, stop):

    scene = nusc.scene[i]

    scene_tokens = []
    token_0 = scene["first_sample_token"]

    while token_0 != "":
      scene_tokens.append(token_0)

      token_sample = nusc.get("sample", token_0)
      token_0 = token_sample["next"]

    for j in range(len(scene_tokens)):
      sample = nusc.get("sample", scene_tokens[j])

      samples.append(sample)

  return samples

def global_augmentation(points, boxes, rotation_range = [-np.pi/4, np.pi/4], scale_range = [0.95,1.05], translate_stdev = .2):
  new_boxes = []

  theta = np.random.uniform(rotation_range[0], rotation_range[1])
  scale = np.random.uniform(scale_range[0], scale_range[1])
  translation = np.random.normal(0, translate_stdev, size = 3)
  x_flip = np.random.rand()
  y_flip = np.random.rand()

  rot_matrix = np.array([[np.cos(theta),-np.sin(theta), 0],[np.sin(theta),np.cos(theta),0],[0,0,1]])

  rot_quat = Quaternion(matrix=rot_matrix)

  points[:, :3] = points[:, :3] @ rot_matrix
  points[:, :3] *= scale
  points[:, :3] += translation

  for box in boxes:
    box.rotate(rot_quat)
    box.center *= scale
    box.wlh *= scale
    box.center += translation

  if x_flip > 0.5:
    points[:, 0] *= -1
    for box in boxes:
      box.center[0] *= -1
      alpha = get_yaw(box.orientation)
      new_alpha = np.pi-alpha
      box.orientation = Quaternion(axis=[0, 0, 1], radians=new_alpha)

  if y_flip > 0.5:
    points[:, 1] *= -1
    for box in boxes:
      box.center[1] *= -1
      alpha = get_yaw(box.orientation)
      new_alpha = -alpha
      box.orientation = Quaternion(axis=[0, 0, 1], radians=new_alpha)

def get_box_names(boxes):

  labels = []

  for i in range(len(boxes)):

    name = boxes[i].name

    labels.append(name)

  return labels


def get_samples(scenes, nusc):

  samples = []

  for scene_name in scenes:
    scene_0 = next(
    (scene for scene in nusc.scene if scene['name'] == scene_name), None
    )
    token_0 = scene_0["first_sample_token"]

    while token_0 != "":

      token_sample = nusc.get("sample", token_0)
      samples.append(token_sample)
      token_0 = token_sample["next"]

  return samples

def cloud_filter_pcrange(points, pc_range = [-51.2, 51.2]):

  mask = (
    (points[:, 0] >= pc_range[0]) & (points[:, 0] < pc_range[1]) &
    (points[:, 1] >= pc_range[0]) & (points[:, 1] < pc_range[1])
  )

  return points[mask]

def boxes_filter_pcrange(boxes, pc_range=[-51.2, 51.2]):

  keep_boxes, keep_names = [], []

  for box in boxes:
    c = box.center

    if (c[0] >= pc_range[0] and c[0] < pc_range[1] and
        c[1] >= pc_range[0] and c[1] < pc_range[1]):
      keep_boxes.append(box)
      keep_names.append(box.name)


  return keep_boxes, keep_names

def IoU(center_a0, center_b0):

    center_a = center_a0.clone().detach().cpu()
    center_b = center_b0.clone().detach().cpu()

    l_a, w_a, h_a = center_a[0], center_a[1], center_a[2]
    x_a, y_a, z_a = center_a[5], center_a[6], center_a[7]
    sin_a, cos_a = center_a[3], center_a[4]

    l_b, w_b, h_b = center_b[0], center_b[1], center_b[2]
    x_b, y_b, z_b = center_b[5], center_b[6], center_b[7]
    sin_b, cos_b = center_b[3], center_b[4]

    scale_a = np.exp(np.array([l_a, w_a, h_a]))
    scale_b = np.exp(np.array([l_b, w_b, h_b]))

    translation_a = np.array([x_a, y_a, z_a])
    translation_b = np.array([x_b, y_b, z_b])

    rotation_a = np.array([[cos_a, -1*sin_a,0],[sin_a, cos_a,0],[0,0,1]])
    rotation_b = np.array([[cos_b, -1*sin_b,0],[sin_b, cos_b,0],[0,0,1]])

    box_a = BoxIoU.from_transformation(rotation_a, translation_a, scale_a)
    box_b = BoxIoU.from_transformation(rotation_b, translation_b, scale_b)

    iou = IoU3d(box_a, box_b)

    return iou.iou()

def boxes_to_tensor(boxes):

  boxes_tensor = []

  for box in boxes:
    center = torch.from_numpy(box.center)
    alpha = box.orientation.radians
    size = torch.from_numpy(box.wlh)

    rotation = torch.tensor([np.sin(alpha), np.cos(alpha)])

    boxes_tensor.append(torch.cat([size, rotation, center]))

  boxes_tensor = torch.stack(boxes_tensor)

  return boxes_tensor