# -*- coding: utf-8 -*-
"""lidar_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1brysJmuPs8Q2MRkadooNKMz1w3RH-k9G
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

import os
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/MyDrive/LIDAR_Fusion/lidarenv/lib/python3.12/site-packages')

from voxel_pointnet2 import PointNetSetAbstraction

def extract_clouds(scene, data_root):

  scene_tokens = []
  token_0 = scene["first_sample_token"]

  while token_0 != "":
    scene_tokens.append(token_0)

    token_sample = nusc.get("sample", token_0)
    token_0 = token_sample["next"]

  scene_clouds = []

  for i in range(len(scene_tokens)):
    cloud_sample = nusc.get("sample", scene_tokens[i])
    cloud_data = nusc.get("sample_data", cloud_sample["data"]["LIDAR_TOP"])

    cloud_root = os.path.join(data_root, cloud_data["filename"])

    cloud = LidarPointCloud.from_file(cloud_root)

    cloud_xyz = cloud.points[:3, :].T

    lidar_cloud = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(cloud_xyz))

    scene_clouds.append(lidar_cloud)

  return scene_clouds

def get_point_pillar(point, min, voxel_size, cols):

  i = np.floor((point[0]-min[0])/voxel_size)
  j = np.floor((point[1]-min[1])/voxel_size)

  pillar_index = (j*cols + i).astype(int)


  return pillar_index

def get_ij(point, min, voxel_size):


  i = (point[0]-min[0]) // voxel_size
  j = (point[1]-min[1]) // voxel_size

  i = int(i.item())
  j = int(j.item())


  return i,j

def get_grid_shape(cloud, voxel_size = 1):
  voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(cloud, voxel_size=voxel_size)

  min_bound = voxel_grid.get_min_bound()
  max_bound = voxel_grid.get_max_bound()

  voxel_shape = np.ceil((max_bound - min_bound) / voxel_size).astype(int)

  return voxel_shape

def get_pillars(cloud, voxel_size = 1, pillar_max = 100): #voxel_size is length of one side of voxel

  voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(cloud, voxel_size=voxel_size)

  min_bound = voxel_grid.get_min_bound()
  max_bound = voxel_grid.get_max_bound()


  voxel_shape = np.ceil((max_bound - min_bound) / voxel_size).astype(int)

  cloud_array = np.asarray(cloud.points)

  T = voxel_shape[0]*voxel_shape[1]

  N_counter = np.zeros(T)

  for k in range(cloud_array.shape[0]):
    point = cloud_array[k]

    p_index = get_point_pillar(point, min_bound, voxel_size, voxel_shape[0])

    N_counter[p_index] += 1

  N = (np.max(N_counter)).astype(int)

  if pillar_max < N or pillar_max == None:
    N = pillar_max

  out = np.zeros((T, N, 3))

  mask = np.zeros((T), dtype = int)

  for m in range(cloud_array.shape[0]):
    point = cloud_array[m]

    p_index = get_point_pillar(point, min_bound, voxel_size, voxel_shape[0])

    k = mask[p_index]

    if k < N:
      out[p_index][k] = point

      mask[p_index] += 1

  out_zeros = ~np.all(out == 0, axis=(1, 2))

  out = out[out_zeros,:,:]

  mask = mask[mask != 0] #mask returns how many non-padded points are in each pillar. Zero points in a pillar are assumed to be padded unless the mask indicates otherwise

  out = torch.from_numpy(out).float()
  mask = torch.from_numpy(mask).float()

  return out, mask

class PillarsEncoder(nn.Module):


  def __init__(self, extra_features = 0, sa1_npoint=16, sa1_radius=0.6, sa1_nsample=16, sa1_mlp=[32, 64], sa2_mlp=[64, 128, 256]):

    super().__init__()
    self.sa1 = PointNetSetAbstraction(npoint=sa1_npoint, radius=sa1_radius, nsample=sa1_nsample, in_channel=3 + extra_features, mlp_channels=sa1_mlp, group_all=False)
    self.aggregate = PointNetSetAbstraction(npoint = None, radius = None, nsample = None, in_channel = 3 + sa1_mlp[-1], mlp_channels = sa2_mlp, group_all = True)

    self.out_dim = sa2_mlp[-1]

  def forward(self, pillars, num_points):

    B, N, C = pillars.shape

    arr = torch.arange(N, device = num_points.device).unsqueeze(0)
    mask = arr < num_points.unsqueeze(1)

    xyz = pillars[..., :3].clone()

    if C > 3:
      feats = pillars[..., 3:]

    else:
      feats = None

    sums = (xyz * mask.unsqueeze(-1)).sum(dim=1)
    centers = sums / num_points.clamp(min=1).unsqueeze(-1).to(xyz.dtype)
    xyz = (xyz - centers.unsqueeze(1)) * mask.unsqueeze(-1)

    l1_xyz, l1_points, l1_mask = self.sa1(xyz, feats, mask)

    _, l2_points, _ = self.aggregate(l1_xyz, l1_points, l1_mask)

    return l2_points.squeeze(1)

def get_centroids(pillars, mask):

  centroids = torch.zeros((pillars.shape[0],pillars.shape[-1]))

  for i in range(pillars.shape[0]):
    sum = pillars[i].sum(axis = 0)
    centroids[i] = sum/mask[i]

  return centroids

def get_feature_map(feats, centroids, cloud, voxel_size): #feature map should be reshapped and padded to be square

  voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(cloud, voxel_size=voxel_size)

  min_bound = voxel_grid.get_min_bound()
  max_bound = voxel_grid.get_max_bound()

  voxel_shape = np.ceil((max_bound - min_bound) / voxel_size).astype(int)

  map = torch.zeros((voxel_shape[0],voxel_shape[1],feats.shape[-1]))

  for k in range(centroids.shape[0]):
    i, j = get_ij(centroids[k],min_bound, voxel_size)
    map[i][j] = feats[k]

  return map
