# -*- coding: utf-8 -*-
"""NuscenesEval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10txSVkHwYne7mlsTpgptax2vIpWzr7t5
"""

import os
import numpy as np
import pickle

from google.colab import drive
drive.mount("/content/drive", force_remount = False)

import torch
import torch.nn as nn
import torch.nn.functional as F

TORCH_version = torch.__version__.split('+')[0]
#CUDA_version = torch.version.cuda.replace('.', '')

#!pip install torch-scatter torch-sparse torch-cluster -f https://data.pyg.org/whl/torch-{TORCH_version}+cu{CUDA_version}.html

#import torch_sparse

import sys
sys.path.append('/content/drive/MyDrive/LIDAR_Fusion/fusionenv/lib/python3.12/site-packages')

#!pip install import-ipynb
#import import_ipynb

#!pip install open3d plotly
#import open3d as o3d

import matplotlib.pyplot as plt
import json

sys.path.insert(0, '/content')

from objectron.dataset.iou import IoU as IoU3d
from objectron.dataset.box import Box as BoxIoU

from nuscenes.nuscenes import NuScenes
from nuscenes.utils.data_classes import LidarPointCloud, Box
from nuscenes.eval.detection.utils import category_to_detection_name
from nuscenes.utils.geometry_utils import points_in_box
from nuscenes.eval.detection.evaluate import DetectionEval
from nuscenes.eval.detection.data_classes import DetectionConfig
from nuscenes.eval.detection.config import config_factory

from pyquaternion import Quaternion

sys.path.insert(0, '/content/drive/MyDrive/LiDARFusion')

import lidartrainlibrary as ltb

def label_to_category(k):
  categories = ["barrier", "bicycle", "bus", "car", "construction_vehicle", "motorcycle", "pedestrian", "traffic_cone", "trailer", "truck"]

  return categories[k]

#[l, w, h, sin, cos, x,y,z ,k, I]

def results_to_json(nusc, boxes_per_sample, sample_tokens, out_path, use_camera=True):
    results = {}
    for i in range(len(sample_tokens)):
        formatted = []
        sample = nusc.get('sample', sample_tokens[i])
        sd_rec = nusc.get('sample_data', sample['data']['LIDAR_TOP'])
        ego_pose = nusc.get('ego_pose', sd_rec['ego_pose_token'])  
        cal_sensor = nusc.get('calibrated_sensor', sd_rec['calibrated_sensor_token'])

        R_cal = Quaternion(cal_sensor['rotation'])
        t_cal = np.array(cal_sensor['translation'])
        R_ego = Quaternion(ego_pose['rotation'])
        t_ego = np.array(ego_pose['translation'])

        for box in boxes_per_sample[i]:
            box_size = np.exp(np.array([box[0], box[1], box[2]]))
            raw_translation = np.array([box[5], box[6], box[7]])

            rot_matrix = np.array([[box[4], -box[3], 0],
                                    [box[3],  box[4], 0],
                                    [0,       0,      1]])
            raw_rotation = Quaternion(matrix=rot_matrix)

            # sensor -> ego
            p_ego = R_cal.rotate(raw_translation) + t_cal
            rot_ego = R_cal * raw_rotation

            # ego -> global
            translation = R_ego.rotate(p_ego) + t_ego
            rotation = R_ego * rot_ego

            box_dict = {
                "sample_token": sample_tokens[i],
                "size": box_size.tolist(),
                "translation": translation.tolist(),
                "rotation": rotation.elements.tolist(),
                "velocity": [0.0, 0.0],
                "detection_name": label_to_category(int(box[8])),
                "detection_score": box[9].item(),
                "attribute_name": "",
            }
            formatted.append(box_dict)

        results[sample_tokens[i]] = formatted
    submission = {
        "meta": {
            "use_camera": use_camera,
            "use_lidar": True,
            "use_radar": False,
            "use_map": False,
            "use_external": False,
        },
        "results": results,
    }
    with open(out_path, 'w') as f:
        json.dump(submission, f)
    return out_path

def run_eval(nusc, result_path, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    cfg = config_factory('detection_cvpr_2019')  # standard nuScenes detection config

    nusc_eval = DetectionEval(
        nusc,
        config=cfg,
        result_path=result_path,
        eval_set='mini_val',
        output_dir=output_dir,
        verbose=True,
    )
    metrics_summary = nusc_eval.main(plot_examples=0, render_curves=False)

    return metrics_summary

